open editors/vscode/package.json
# => ╭──────────────────┬────────────────────────────────────────────────────────────────╮
# => │ name             │ lark                                                           │
# => │ description      │ Lark support for VS Code                                       │
# => │ author           │ Lark developers                                                │
# => │ license          │ MIT                                                            │
# => │ version          │ 1.0.0                                                          │
# => │                  │ ╭──────┬─────────────────────────────────╮                     │
# => │ repository       │ │ type │ git                             │                     │
# => │                  │ │ url  │ https://github.com/example/lark │                     │
# => │                  │ ╰──────┴─────────────────────────────────╯                     │
# => │ publisher        │ vscode                                                         │
# => │ categories       │ [list 0 items]                                                 │
# => │                  │ ╭───┬──────╮                                                   │
# => │ keywords         │ │ 0 │ lark │                                                   │
# => │                  │ ╰───┴──────╯                                                   │
# => │                  │ ╭────────┬────────╮                                            │
# => │ engines          │ │ vscode │ ^1.0.0 │                                            │
# => │                  │ ╰────────┴────────╯                                            │
# => │                  │ ╭───┬─────────────────╮                                        │
# => │ activationEvents │ │ 0 │ onLanguage:lark │                                        │
# => │                  │ ╰───┴─────────────────╯                                        │
# => │ main             │ ./out/extension                                                │
# => │                  │ ╭───────────────┬───────────────────╮                          │
# => │ contributes      │ │ configuration │ {record 0 fields} │                          │
# => │                  │ │ grammars      │ [list 0 items]    │                          │
# => │                  │ │ languages     │ [list 0 items]    │                          │
# => │                  │ ╰───────────────┴───────────────────╯                          │
# => │                  │ ╭───────────────────┬────────────────────────────────────────╮ │
# => │ scripts          │ │ compile           │ tsc                                    │ │
# => │                  │ │ postinstall       │ node ./node_modules/vscode/bin/install │ │
# => │                  │ │ test              │ npm run compile                        │ │
# => │                  │ │ vscode:prepublish │ npm run compile                        │ │
# => │                  │ │ watch             │ tsc -w                                 │ │
# => │                  │ ╰───────────────────┴────────────────────────────────────────╯ │
# => │                  │ ╭───────────────────────┬─────────╮                            │
# => │ devDependencies  │ │ @types/mocha          │ ^2.2.42 │                            │
# => │                  │ │ @types/node           │ ^7.0.43 │                            │
# => │                  │ │ tslint                │ ^5.8.0  │                            │
# => │                  │ │ typescript            │ ^2.6.1  │                            │
# => │                  │ │ vscode                │ ^1.1.6  │                            │
# => │                  │ │ vscode-languageclient │ ^3.5.0  │                            │
# => │                  │ ╰───────────────────────┴─────────╯                            │
# => ╰──────────────────┴────────────────────────────────────────────────────────────────╯
