import type { SidebarConfig } from '@vuepress/theme-default';
// import { commandCategories } from './command_categories';

export const sidebarJa: SidebarConfig = {
  '/ja/book/': [
    {
      text: 'はじめに',
      link: '/ja/book/README.md',
      collapsible: false,
    },
    {
      text: 'Getting Started',
      link: '/ja/book/getting_started.md',
      collapsible: false,
      children: [
        '/ja/book/installation.md',
        '/book/default_shell.md',
        '/ja/book/quick_tour.md',
        '/ja/book/moving_around.md',
        '/book/thinking_in_nu.md',
        '/book/cheat_sheet.md',
      ],
    },
    {
      text: 'Nu 基礎編',
      link: '/ja/book/nu_fundamentals.md',
      collapsible: false,
      children: [
        '/ja/book/types_of_data.md',
        '/ja/book/loading_data.md',
        '/ja/book/pipelines.md',
        '/book/working_with_strings.md',
        '/book/working_with_lists.md',
        '/ja/book/working_with_tables.md',
      ],
    },
    {
      text: 'Programming in Nu',
      link: '/ja/book/programming_in_nu.md',
      collapsible: false,
      children: [
        '/book/custom_commands.md',
        '/ja/book/aliases.md',
        '/book/operators.md',
        '/book/variables_and_subexpressions.md',
        '/book/scripts.md',
        '/book/modules.md',
        '/book/overlays.md',
        '/book/command_signature.md',
        '/book/testing.md',
        '/book/style_guide.md',
      ],
    },
    {
      text: 'シェルとしての Nu',
      link: '/ja/book/nu_as_a_shell.md',
      collapsible: false,
      children: [
        '/ja/book/configuration.md',
        '/ja/book/environment.md',
        '/book/stdout_stderr_exit_codes.md',
        '/ja/book/escaping.md',
        '/book/3rdpartyprompts.md',
        '/ja/book/shells_in_shells.md',
        '/book/line_editor.md',
        '/book/externs.md',
        '/book/custom_completions.md',
        '/book/coloring_and_theming.md',
        '/book/hooks.md',
        '/book/background_task.md',
      ],
    },
    {
      text: 'Nu への移行',
      link: '/ja/book/coming_to_nu.md',
      collapsible: false,
      children: [
        '/ja/book/coming_from_bash.md',
        '/book/coming_from_cmd.md',
        '/ja/book/nushell_map.md',
        '/ja/book/nushell_map_imperative.md',
        '/ja/book/nushell_map_functional.md',
        '/ja/book/nushell_operator_map.md',
      ],
    },
    {
      text: 'Design Notes',
      link: '/ja/book/design_notes.md',
      collapsible: false,
      children: ['/book/how_nushell_code_gets_run.md'],
    },
    {
      text: '(Not So) Advanced',
      link: '/ja/book/advanced.md',
      collapsible: false,
      children: [
        '/book/standard_library.md',
        '/book/dataframes.md',
        '/ja/book/metadata.md',
        '/book/creating_errors.md',
        '/book/parallelism.md',
        '/ja/book/plugins.md',
        '/book/explore.md',
      ],
    },
  ],
  // '/commands/': [
  //   {
  //     text: 'Categories',
  //     collapsible: false,
  //     children: commandCategories,
  //   },
  // ],
  // '/ja/contributor-book/': [
  //   {
  //     text: 'Contributor Book',
  //     link: '/contributor-book/README.md',
  //     collapsible: false,
  //     children: [
  //       'README.md',
  //       'philosophy',
  //       'philosophy_0_80',
  //       'commands',
  //       'plugins',
  //     ],
  //   },
  // ],
  // '/ja/cookbook/': [
  //   {
  //     text: 'Cookbook',
  //     collapsible: false,
  //     children: [
  //       'README.md',
  //       'setup',
  //       'help',
  //       'system',
  //       'parsing',
  //       'pattern_matching',
  //       'external_completers',
  //       'files',
  //       'git',
  //       'parsing_git_log',
  //       'http',
  //       'direnv',
  //       'ssh_agent',
  //       'tables',
  //       'polars_v_pandas_v_nushell',
  //       'jq_v_nushell',
  //     ],
  //   },
  // ],
};
