import type { SidebarConfig } from '@vuepress/theme-default';
import { commandCategories } from './command_categories';

export const sidebarZhCN: SidebarConfig = {
  '/zh-CN/book/': [
    {
      text: '简介',
      link: '/zh-CN/book/README.md',
      collapsible: false,
    },
    {
      text: '安装',
      link: '/zh-CN/book/installation.md',
      collapsible: false,
      children: ['/zh-CN/book/default_shell.md'],
    },
    {
      text: '快速入门',
      link: '/zh-CN/book/getting_started.md',
      collapsible: false,
      children: [
        '/zh-CN/book/quick_tour.md',
        '/zh-CN/book/moving_around.md',
        '/zh-CN/book/thinking_in_nu.md',
        '/zh-CN/book/cheat_sheet.md',
      ],
    },
    {
      text: 'Nu 基础篇',
      link: '/zh-CN/book/nu_fundamentals.md',
      collapsible: false,
      children: [
        '/zh-CN/book/types_of_data.md',
        '/zh-CN/book/loading_data.md',
        '/zh-CN/book/pipelines.md',
        '/zh-CN/book/working_with_strings.md',
        '/zh-CN/book/working_with_lists.md',
        '/zh-CN/book/working_with_records.md',
        '/zh-CN/book/working_with_tables.md',
        '/zh-CN/book/navigating_structured_data.md',
        '/zh-CN/book/special_variables.md',
      ],
    },
    {
      text: 'Nushell 编程',
      link: '/zh-CN/book/programming_in_nu.md',
      collapsible: false,
      children: [
        '/zh-CN/book/custom_commands.md',
        '/zh-CN/book/aliases.md',
        '/zh-CN/book/operators.md',
        '/zh-CN/book/variables.md',
        '/zh-CN/book/control_flow.md',
        '/zh-CN/book/scripts.md',
        {
          text: '模块',
          link: '/zh-CN/book/modules.md',
          collapsible: false,
          children: [
            '/zh-CN/book/modules/using_modules.md',
            '/zh-CN/book/modules/creating_modules.md',
          ],
        },
        '/zh-CN/book/overlays.md',
        '/zh-CN/book/sorting.md',
        '/zh-CN/book/testing.md',
        '/zh-CN/book/style_guide.md',
      ],
    },
    {
      text: 'Nu 作为 Shell 使用',
      link: '/zh-CN/book/nu_as_a_shell.md',
      collapsible: false,
      children: [
        '/zh-CN/book/configuration.md',
        '/zh-CN/book/environment.md',
        '/zh-CN/book/stdout_stderr_exit_codes.md',
        '/zh-CN/book/running_externals.md',
        '/zh-CN/book/3rdpartyprompts.md',
        '/zh-CN/book/directory_stack.md',
        '/zh-CN/book/line_editor.md',
        '/zh-CN/book/custom_completions.md',
        '/zh-CN/book/externs.md',
        '/zh-CN/book/coloring_and_theming.md',
        '/zh-CN/book/hooks.md',
        '/zh-CN/book/background_jobs.md',
      ],
    },
    {
      text: '迁移到 Nu',
      link: '/zh-CN/book/coming_to_nu.md',
      collapsible: false,
      children: [
        '/zh-CN/book/coming_from_bash.md',
        '/zh-CN/book/coming_from_cmd.md',
        '/zh-CN/book/nushell_map.md',
        '/zh-CN/book/nushell_map_imperative.md',
        '/zh-CN/book/nushell_map_functional.md',
        '/zh-CN/book/nushell_operator_map.md',
      ],
    },
    {
      text: '设计说明',
      link: '/zh-CN/book/design_notes.md',
      collapsible: false,
      children: ['/zh-CN/book/how_nushell_code_gets_run.md'],
    },
    {
      text: '（不怎么）高级篇',
      link: '/zh-CN/book/advanced.md',
      collapsible: false,
      children: [
        '/zh-CN/book/standard_library.md',
        '/zh-CN/book/dataframes.md',
        '/zh-CN/book/metadata.md',
        '/zh-CN/book/creating_errors.md',
        '/zh-CN/book/parallelism.md',
        '/zh-CN/book/plugins.md',
        '/zh-CN/book/explore.md',
      ],
    },
  ],
  '/commands/': [
    {
      text: '命令分类',
      collapsible: false,
      children: commandCategories,
    },
  ],
  '/zh-CN/contributor-book/': [
    {
      text: '贡献者指南',
      link: '/zh-CN/contributor-book/README.md',
      collapsible: false,
      children: [
        '/zh-CN/contributor-book/README.md',
        '/zh-CN/contributor-book/philosophy',
        '/zh-CN/contributor-book/philosophy_0_80',
        '/zh-CN/contributor-book/commands',
        '/zh-CN/contributor-book/plugins',
        '/zh-CN/contributor-book/plugin_protocol_reference',
      ],
    },
  ],
  '/zh-CN/cookbook/': [
    {
      text: '实战指南',
      collapsible: false,
      children: [
        '/zh-CN/cookbook/README.md',
        '/zh-CN/cookbook/setup',
        '/zh-CN/cookbook/help',
        '/zh-CN/cookbook/system',
        '/zh-CN/cookbook/parsing',
        '/zh-CN/cookbook/foreign_shell_scripts',
        '/zh-CN/cookbook/pattern_matching',
        '/zh-CN/cookbook/custom_completers',
        '/zh-CN/cookbook/external_completers',
        '/zh-CN/cookbook/modules',
        '/zh-CN/cookbook/files',
        '/zh-CN/cookbook/git',
        '/zh-CN/cookbook/parsing_git_log',
        '/zh-CN/cookbook/input_listen_keys',
        '/zh-CN/cookbook/http',
        '/zh-CN/cookbook/direnv',
        '/zh-CN/cookbook/ssh_agent',
        '/zh-CN/cookbook/tables',
        '/zh-CN/cookbook/polars_v_pandas_v_nushell',
        '/zh-CN/cookbook/jq_v_nushell',
      ],
    },
  ],
};
