export * from './de.js';
export * from './en.js';
export * from './es.js';
export * from './fr.js';
export * from './ja.js';
export * from './pt-BR.js';
export * from './ru.js';
export * from './zh-CN.js';
export * from './ko.js';
